//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnPol.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agente
    {
        public int IdAgente { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Placa { get; set; }
        public string Direecion { get; set; }
        public string Telefono { get; set; }
    }
}
